---
title: Advanced level Analysis
format:
  html:
    code-fold: true
---

```{r include=FALSE}
suppressPackageStartupMessages(library(tidyverse))
library(googlesheets4)
library(cowplot)
library(stringr)
knitr::opts_chunk$set(message=FALSE, fig.width=16, fig.height=12)
```

```{r setup_gsheets, message=FALSE, incluce=FALSE}
gs4_auth(email='dschneid@gmail.com')
Sheet = "https://docs.google.com/spreadsheets/d/1252VDsq9N21Zrl21zkEx0TOjXeKmOddHrwno1xhrEsI/edit?resourcekey#gid=983704671"
```

```{r read_favorites, include=FALSE}
fav_trails = read_sheet(Sheet, sheet="favorite_trails")

activity_levels = c("Beginner","Intermediate","Advanced")
cleaned_fav_trails <-
fav_trails %>%
mutate(
    season = case_when(activity %in% c("mountain biking", "(trail) running", "hiking") ~ "summer", TRUE ~ "winter"),
    activity = as_factor(activity),
        level = case_when(level %in% activity_levels ~ level, TRUE ~ "Intermediate"),
        level = factor(level, activity_levels))

```

```{r read_freq, cache=TRUE, include=FALSE}
freq_trails = read_sheet(Sheet, sheet="frequented_trails")

activity_levels = c("Beginner","Intermediate","Advanced")
cleaned_freq_trails <-
freq_trails %>%
mutate(
    season = case_when(activity %in% c("mountain biking", "(trail) running", "hiking") ~ "summer", TRUE ~ "winter"),
    activity = as_factor(activity),
        level = case_when(level %in% activity_levels ~ level, TRUE ~ "Intermediate"),
        level = factor(level, activity_levels))
```

```{r read_trail_experiences, cache=TRUE, include=FALSE}
experiences = read_sheet(Sheet, sheet="trail_experiences")

activity_levels = c("Beginner","Intermediate","Advanced")
cleaned_experiences <-
experiences %>%
mutate(
    experience = as.factor(experience),
    season = case_when(activity %in% c("mountain biking", "(trail) running", "hiking") ~ "summer", TRUE ~ "winter"),
    activity = as.factor(activity),
    level = case_when(level %in% activity_levels ~ level, TRUE ~ "Intermediate"),
    level = factor(level, activity_levels))


experience_colors = RColorBrewer::brewer.pal(n=9, name="Set1")
names(experience_colors)= levels(cleaned_experiences$experience)
```

# Experiences of Favorite Trails

```{r}
top_n_fav =
cleaned_fav_trails %>%
filter(activity %in% c("mountain biking", "(trail) running"), level %in% c("Intermediate","Advanced")) %>%
select(activity, level, favorite_trail) %>%
group_by(activity, level, favorite_trail, .drop=TRUE) %>%
summarise(
    n=n()) %>%
slice_max(n=5, order_by=n) %>%
select(activity, favorite_trail, level)


```

```{r}
fav_exp = cleaned_experiences %>%
select(activity, trail, experience, level) %>%
inner_join(top_n_fav, by=c("trail"="favorite_trail", "activity"="activity", "level"="level"))

group_response_rate = fav_exp %>%
group_by(activity, level) %>%
summarize(
    max_n = n()
)

fav_exp %>%
group_by(activity, level, trail, experience) %>%
add_count() %>%
left_join(group_response_rate) %>%
mutate(exp_prop = n / max_n) %>%
filter(!experience %in% c("Education","Nature")) %>%
ggplot()+
geom_col(aes(x=trail, y=exp_prop, fill=experience), position='dodge')+
facet_wrap(level~activity)+
scale_fill_brewer(palette='Set1', drop=FALSE)+
theme(axis.text.x = element_text(angle=45, vjust=1, hjust=1),
axis.text = element_text(size=18),
text = element_text(size=20))
```
```{r}
ggsave(plot=.Last.value, filename="experiences_of_top_n_fav_trails.png", dpi=150, width=16, height=8)
```

# Experiences of Frequented Trails

```{r}
top_n_freq = cleaned_freq_trails %>%
filter(activity %in% c("mountain biking", "(trail) running"), level %in% c("Intermediate","Advanced")) %>%
select(activity, level, most_frequented_trail) %>%
group_by(activity, level, most_frequented_trail, .drop=TRUE) %>%
summarise(
    n=n()) %>%
slice_max(n=5, order_by=n) %>%
select(activity, most_frequented_trail, level)


```

```{r}
freq_exp = cleaned_experiences %>%
select(activity, trail, experience, level) %>%
inner_join(top_n_freq, by=c("trail"="most_frequented_trail", "activity"="activity", "level"="level"))

group_response_rate = freq_exp %>%
group_by(activity, level) %>%
summarize(
    max_n = n()
)

freq_exp %>%
group_by(activity, level, trail, experience) %>%
add_count() %>%
left_join(group_response_rate) %>%
mutate(exp_prop = n / max_n) %>%
# filter(!experience %in% c("Education","Nature")) %>%
ggplot()+
geom_col(aes(x=trail, y=exp_prop, fill=experience), position='dodge')+
facet_wrap(level~activity)+
scale_fill_brewer(palette='Set1', drop=FALSE)+
theme(axis.text.x = element_text(angle=45, vjust=1, hjust=1),
axis.text = element_text(size=18),
text = element_text(size=20))

ggsave(plot=.Last.value, filename="experiences_of_top_n_frequented_trails.png", dpi=150, height=8, width=16)

```
