---
title: Favorites Analysis

---



```{r}
suppressPackageStartupMessages(library(tidyverse))
library(googlesheets4)
library(stringr)
gs4_auth(email='dschneid@gmail.com')
Sheet = "https://docs.google.com/spreadsheets/d/1252VDsq9N21Zrl21zkEx0TOjXeKmOddHrwno1xhrEsI/edit?resourcekey#gid=983704671"
fav_trails = read_sheet(Sheet, sheet="favorite_trails")
fav_trails %>% colnames()

```

```{r}
activity_levels = c("Beginner","Intermediate","Advanced")
cleaned_fav_trails <-
fav_trails %>%
mutate(
    season = case_when(activity %in% c("mountain biking", "(trail) running", "hiking") ~ "summer", TRUE ~ "winter"),
    activity = as_factor(activity),
        level = case_when(level %in% activity_levels ~ level, TRUE ~ "Intermediate"),
        level = factor(level, activity_levels))

```

```{r}
cleaned_fav_trails %>%
ggplot()+geom_bar(aes(y=fct_infreq(favorite_trail)))+ggtitle("Overall Favorite Trails")
```

```{r}
cleaned_fav_trails %>%
distinct(timestamp, activity) %>%
ggplot() + geom_bar(aes(y=activity))

```

```{r}
cleaned_fav_trails %>%
distinct(timestamp, activity, level) %>%
ggplot() + geom_bar(aes(y=activity)) + facet_wrap(~level)
```

```{r}
cleaned_fav_trails %>%
filter(season == "summer", level != "Beginner", activity != "hiking") %>%
ggplot() + geom_bar(aes(y=fct_infreq(favorite_trail))) +
    facet_grid(rows=vars(activity), cols=vars(level))
```

```{r}
cleaned_fav_trails %>%
filter(season == "summer", level != "Beginner", activity == "hiking") %>%
ggplot() + geom_bar(aes(y=fct_infreq(favorite_trail))) +
    facet_grid(rows=vars(activity), cols=vars(level))
```

```{r}

```
