---
title: User Experience Analysis
format:
  html:
    code-fold: true
editor:
  render-on-save: true
---


```{r, cache=TRUE}
suppressPackageStartupMessages(library(tidyverse))
library(googlesheets4)
library(stringr)
gs4_auth(email="dschneid@gmail.com")
Sheet = "https://docs.google.com/spreadsheets/d/1252VDsq9N21Zrl21zkEx0TOjXeKmOddHrwno1xhrEsI/edit?resourcekey#gid=983704671"
experiences = read_sheet(Sheet, sheet="trail_experiences")


```

```{r, include=FALSE}
activity_levels = c("Beginner","Intermediate","Advanced")
cleaned_experiences <- experiences %>%
mutate(
    season = case_when(activity %in% c("mountain biking", "(trail) running", "hiking") ~ "summer", TRUE ~ "winter"),
    activity = as_factor(activity),
        level = case_when(level %in% activity_levels ~ level, TRUE ~ "Intermediate"),
        level = factor(level, activity_levels))

```


```{r eval=FALSE}
num_users <- cleaned_experiences %>%
distinct(timestamp) %>%
count()
num_trails <- cleaned_experiences %>%
  distinct(trail)

num_trails$trail



```

# Which experience is most represented?

```{r}
ggplot(cleaned_experiences)+
geom_bar(aes(x=experience), stat="count")+
ggtitle('Count of experiences')

ggsave(plot=.Last.value, filename="count_of_experiences.png", dpi=150)
```

```{r}
ggplot(cleaned_experiences)+
geom_bar(aes(x=trail, fill=experience), stat='count', position='dodge')+
theme(axis.text.x = element_text(angle=90, hjust=1, vjust=.5))+
scale_fill_brewer(palette = "Set1")

```

# Which experiences are most represented?

```{r, results='asis'}
top_experiences = cleaned_experiences %>%
group_by(activity, level, trail) %>%
count(experience) %>%
group_by(experience) %>%
summarise(
    max_n = max(n)
) %>%
slice_max(prop=.5, order_by=max_n)

top_experiences %>% knitr::kable()
```

```{r}
cleaned_experiences %>%
inner_join(top_experiences) %>%
group_by(activity, trail) %>%
count(experience) %>%
ungroup() %>%
arrange(desc(n)) %>%
group_by(activity, trail) %>%
slice_max(prop=0.5, order_by=n) %>%
filter(activity %in% c("mountain biking","(trail) running")) %>%
ggplot()+
geom_bar(aes(x=experience))+
facet_grid(trail~activity)+
theme(axis.text.x=element_text(angle=90, hjust=1, vjust=0.5))
```

```{r}
cleaned_experiences %>%
group_by(activity, level, trail) %>%
count(experience) %>%
group_by(activity, level, experience) %>%
summarise( max_n = max(n)) %>%
ggplot() +
    geom_bar(aes(x=interaction(activity, level), y=max_n, fill=experience), position='dodge', stat='identity')+
    scale_fill_brewer(palette="Set1")+theme(axis.text.x=element_text(angle=90, hjust=1, vjust=.5))
```
